<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easyuser"
 *
 * Auto generated by Extension Builder 2014-10-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FEUser Test Extension',
	'description' => 'This is a test extension to examine the interaction between fe_users and a simple extbase extension.',
	'category' => 'plugin',
	'author' => 'Bernhard Mehler',
	'author_email' => 'bernhard.mehler@gmail.com',
	'state' => 'test',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);