<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblog"
 *
 * Auto generated by Extension Builder 2014-08-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Blog Extension',
	'description' => 'This is the didactical example from the book \"Extbase & Fluid\" by Patrick Lobacher',
	'category' => 'plugin',
	'author' => 'Bernhard Mehler',
	'author_email' => 'bernhard.mehler@gmail.com',
	'author_company' => '30gradwarm',
	'shy' => '',
	'priority' => 'top',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>