<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleproject"
 *
 * Auto generated by Extension Builder 2014-11-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Project Extension',
	'description' => 'This is a didactical extension by Bernhard Mehler',
	'category' => 'plugin',
	'author' => 'Bernhard Mehler',
	'author_email' => 'bernhard.mehler@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);